Remove https dependency
gofynd/fdk-cli pull request #144
Opened 2022-09-19 07:24 UTC by Shivraj0

**JIRA: ** https://gofynd.atlassian.net/browse/FPCO-3570

2022-09-19 08:55 UTC, vivek8690 commented on src/helper/serve.utils.ts
> -	const app = require('https-localhost')(getLocalBaseUrl());
remove dependency from package.json also @Shivraj0

2022-09-19 08:55 UTC, vivek8690 requested changes
Add requested changes

2022-09-19 09:48 UTC, Shivraj0 commented on src/helper/serve.utils.ts
> -	const app = require('https-localhost')(getLocalBaseUrl());
Done

2023-01-03 07:25 UTC, vivek8690 approved these changes

2023-01-03 07:26 UTC, merged