Add test case automation
gofynd/fdk-cli pull request #149
Opened 2022-09-27 07:25 UTC by Shivraj0

**JIRA: ** https://gofynd.atlassian.net/browse/FPCO-4801

2022-10-03 04:29 UTC, vivek8690 commented on .github/workflows/on_pull_request.yml
> +      - feature-fpco-4801-automation-fixes
remove this @Shivraj0

2022-10-03 04:29 UTC, vivek8690 requested changes
Add requested changes

2022-10-03 05:02 UTC, Shivraj0 commented on .github/workflows/on_pull_request.yml
> +      - feature-fpco-4801-automation-fixes
Done @vivek8690

2022-10-17 12:16 UTC, vivek8690 approved these changes

2022-10-17 12:16 UTC, merged