Add url support in env set command
gofynd/fdk-cli pull request #211
Opened 2023-06-15 13:52 UTC by manishprajapati52

2023-06-16 15:07 UTC, vivek8690 requested changes
Add commented changes @manishprajapati52

2023-06-16 15:07 UTC, vivek8690 commented on src/lib/Env.ts
> +          console.log(err);
Don't use console log @manishprajapati52

2023-06-16 15:07 UTC, vivek8690 commented on src/lib/Env.ts
> +          throw new Error("Provided url is not sandbox URL.")
use `CommandError` instead of  `Error` @manishprajapati52

2023-06-16 15:07 UTC, vivek8690 commented on src/lib/Env.ts
> +            throw new Error("Provided url is not sandbox URL.")
Use CommandError instead of Error @manishprajapati52

2023-06-17 05:38 UTC, manishprajapati52 commented on src/lib/Env.ts
> +          throw new Error("Provided url is not sandbox URL.")
We have catch outside that, there we are catching this error and Passing into CommandError.

2023-06-17 05:39 UTC, manishprajapati52 commented on src/lib/Env.ts
> +            throw new Error("Provided url is not sandbox URL.")
Didn't get this...
Don't use CommandError?

2023-06-22 08:44 UTC, vivek8690 approved these changes

2023-06-22 08:45 UTC, merged