feat development server for fdkcli
gofynd/fdk-cli pull request #253
Opened 2023-09-20 09:21 UTC by amargupta12

2023-09-22 05:29 UTC, ZaidRehmanFynd commented on src/helper/serve.utils.ts
> +                    'x-fp-cli': `${packageJSON.version}`,
Add in react server as well

2023-10-09 07:45 UTC, Shivraj0 requested changes

2023-10-09 07:45 UTC, Shivraj0 commented on src/helper/serve.utils.ts
> +                }
Make it a common var and then use it for both jetfire and skyfire.

2024-01-09 06:28 UTC, Shivraj0 approved these changes

2024-01-09 06:29 UTC, merged