Ts css support
gofynd/fdk-cli pull request #300
Opened 2024-03-15 10:42 UTC by meetdhananifynd

2024-04-05 05:17 UTC, karanrainafynd requested changes
Remove logs

2024-04-05 05:17 UTC, karanrainafynd commented on src/lib/Theme.ts
> +             */
Remove these comments

2024-04-05 05:17 UTC, karanrainafynd commented on src/lib/Theme.ts
> +            // It lets SDK know code is being executed in Node env
remove comments

2024-04-05 05:17 UTC, karanrainafynd commented on src/lib/Theme.ts
> +                console.log(`Settings in ${path} file : `, {settings})
Remove

2024-04-05 05:17 UTC, karanrainafynd commented on src/lib/Theme.ts
> +                console.log(``)
Remove

2024-04-05 05:52 UTC, meetdhananifynd commented on src/lib/Theme.ts
> +            // It lets SDK know code is being executed in Node env
fixed

2024-04-05 05:52 UTC, meetdhananifynd commented on src/lib/Theme.ts
> +                console.log(`Settings in ${path} file : `, {settings})
done

2024-04-05 05:53 UTC, meetdhananifynd commented on src/lib/Theme.ts
> +                console.log(``)
done

2024-04-05 05:53 UTC, meetdhananifynd commented on src/lib/Theme.ts
> +            // It lets SDK know code is being executed in Node env
done

2024-04-09 11:59 UTC, karanrainafynd reviewed
Pls update as per comments

2024-04-09 11:59 UTC, karanrainafynd commented on src/helper/utils.ts
> +        console.error('Error transforming JSX/TSX to JS:', error);
use Logger.error

2024-04-09 12:00 UTC, karanrainafynd commented on src/helper/utils.ts
> +        console.error('Error transforming JSX/TSX to JS:', error);
Fix merge conflicts and align with master

2024-05-16 08:51 UTC, merged