ID:FPTH-6507; DONE: 100; HOURS: 3; Add handler for cloudflare-static …
gofynd/fdk-cli pull request #302
Opened 2024-04-01 08:56 UTC by manishprajapati52

…files

2024-04-02 11:08 UTC, vivek-gofynd requested changes

2024-04-02 11:08 UTC, vivek-gofynd commented on src/helper/serve.utils.ts
> +    publicCache[url] = publicCache[url] || {};
caching is required here ? @manishprajapati52

2024-04-03 02:16 UTC, vivek-gofynd requested changes

2024-04-03 02:16 UTC, vivek-gofynd commented on src/helper/serve.utils.ts
> +            return await requestToOriginalSource(req, res, domain);
What happens if any request get failed here @manishprajapati52

2024-04-03 09:16 UTC, manishprajapati52 commented on src/helper/serve.utils.ts
> +            return await requestToOriginalSource(req, res, domain);
Added error handling.

2024-04-03 09:17 UTC, vivek-gofynd approved these changes

2024-04-05 12:50 UTC, vivek-gofynd approved these changes

2024-04-05 12:51 UTC, merged