2.2.3
gofynd/fdk-cli pull request #58
Opened 2022-05-04 09:34 UTC by Shivraj0

2022-05-05 07:06 UTC, vivek8690 requested changes

2022-05-05 07:06 UTC, vivek8690 commented on src/lib/api/ApiClient.ts
> +    if(response.config.method == 'head'){
Not needed here @Shivraj0

2022-05-05 07:06 UTC, vivek8690 commented on src/lib/api/ApiClient.ts
> +      console.log('Response Error');
remove console log @Shivraj0

2022-05-05 07:06 UTC, vivek8690 commented on src/lib/api/ApiClient.ts
> +      console.log('Request Error');
remove console @Shivraj0

2022-05-05 07:06 UTC, vivek8690 commented on src/lib/api/ApiClient.ts
> +      console.log('Setting up Request Error');
remove console

2022-05-05 07:06 UTC, vivek8690 commented on src/lib/api/ApiClient.ts
> +axios.interceptors.response.use(
create one function inside /helper/interceptors and use it here just like request interceptor

2022-05-05 11:30 UTC, Shivraj0 commented on src/lib/api/ApiClient.ts
> +    if(response.config.method == 'head'){
Done

2022-05-05 11:30 UTC, Shivraj0 commented on src/lib/api/ApiClient.ts
> +      console.log('Response Error');
These logs are added only for debugging purpose, so that when anything breaks it will be easier to point from where it is breaking. Let me know if it is to be removed.

2022-05-05 11:30 UTC, Shivraj0 commented on src/lib/api/ApiClient.ts
> +      console.log('Request Error');
As mentioned above

2022-05-05 11:30 UTC, Shivraj0 commented on src/lib/api/ApiClient.ts
> +      console.log('Setting up Request Error');
As mentioned

2022-05-05 11:30 UTC, Shivraj0 commented on src/lib/api/ApiClient.ts
> +axios.interceptors.response.use(
Done

2022-05-09 02:49 UTC, vivek8690 commented on src/lib/api/helper/interceptors.ts
> +function responseInterceptorFn(response) {
export single response interceptor function and use it as a callback function @Shivraj0

2022-05-09 14:54 UTC, Shivraj0 commented on src/lib/api/helper/interceptors.ts
> +function responseInterceptorFn(response) {
We require 2 different methods for response interceptors.
`1. Handling success response
 2. Handling error response `
 
 Same is done in [SDK](https://gitlab.com/fynd/regrowth/common/sdk/-/blob/master/templates/javascript/code/sdk/common/AxiosHelper.js.nunjucks#L88)
 
 Doc reference: https://axios-http.com/docs/interceptors

2022-05-09 14:54 UTC, Shivraj0 reviewed
Replied on commented query

2022-05-16 12:36 UTC, merged