ID:FPCO-3617 ; DONE: 90; HOURS: 2; FDK theme package command that will generate zip file of theme
gofynd/fdk-cli pull request #85
Opened 2022-07-11 06:54 UTC by anuragpandey1115

2022-07-12 14:56 UTC, vivek8690 commented on src/lib/Theme.ts
> +            throw new CommandError(`Failed to copying theme files to .fdk folder`);
change this error message @anuragpandey1115

2022-07-12 14:56 UTC, vivek8690 requested changes
Change

2022-07-13 06:04 UTC, vivek8690 commented on src/lib/Theme.ts
> +        let Content = JSON.parse(packageContent);
local variables should start with a small letter @anuragpandey1115

2022-07-13 06:04 UTC, vivek8690 reviewed
variable name should start with small letter

2022-10-10 06:59 UTC, Shivraj0 commented
https://github.com/gofynd/fdk-cli/pull/131/

2022-10-10 06:59 UTC, closed without merging